defaults:
  - model: smp
  - dataset: car_segmentation
  - optimizer: adam
  - loss: dice
  - trainer: lightning

model:
  arch: FPN
  encoder_name: resnext50_32x4d
  encoder_weights: imagenet
  in_channels: 3
  out_classes: 1

dataset:
  classes: ["car"]
  data_dir: ./data/CamVid
  batch_size: 32
  num_workers: 0

optimizer:
  lr: 2e-4

trainer:
  max_epochs: 10
