defaults:
  - model: smp
  - dataloader: car_segmentation
  - optimizer: adam
  - loss: dice_binary
  - trainer: lightning

model:
  arch: FPN
  encoder_name: resnext50_32x4d
  encoder_weights: imagenet
  in_channels: 3
  out_classes: 1

dataloader:
  train:
    classes: ["car"]
    images_dir: ./data/CamVid/train
    annotations_dir: ./data/CamVid/trainannot
    augmentation: training
    batch_size: 32
    num_workers: 0
  val:
    classes: ["car"]
    images_dir: ./data/CamVid/val
    annotations_dir: ./data/CamVid/valnannot
    augmentation: validation
    batch_size: 32
    num_workers: 0
  test:
    classes: ["car"]
    images_dir: ./data/CamVid/test
    annotations_dir: ./data/CamVid/testnannot
    augmentation: validation
    batch_size: 32
    num_workers: 0

optimizer:
  lr: 0.0002
  # lr: 2e-4

trainer:
  max_epochs: 10
